[tool.nonebot]
adapters = ["nonebot.adapters.onebot.v11"]
plugins = ["bot.report", "nonebot_plugin_apscheduler"]

[tool.poetry.dependencies]
nonebot2 = "^2.0.0"
nonebot-adapter-onebot = "^2.2.3"
asyncpg = "^0.29.0"
nonebot-plugin-apscheduler = "^0.4.0"
